-- Reversa da supabase/migrations/20261007200300_hml01_treino_grupos_e_permissoes.sql (BANCO DO TREINO): volta ao estado de
-- 07/10/2026 ~19:50 (foto dos privilégios lida do banco antes de aplicar). Mesmo jeito de aplicar: set physiq.schemas = '<schema>';
-- <este arquivo>. As policies e a guarda voltam ao texto antigo; a physiq_pode_ler_grupo sai.
DO $rev$
DECLARE
  sch text;
  alvo text[] := coalesce(string_to_array(nullif(current_setting('physiq.schemas', true), ''), ','), ARRAY['public','staging']);
BEGIN
  FOREACH sch IN ARRAY alvo LOOP
    EXECUTE format('DROP POLICY IF EXISTS "Grupos: leitura do dono, do catalogo e de quem recebe" ON %I.tb_grupos_treino', sch);
    EXECUTE format('DROP POLICY IF EXISTS "Leitura publica grupos" ON %I.tb_grupos_treino', sch);
    EXECUTE format('CREATE POLICY "Leitura publica grupos" ON %I.tb_grupos_treino FOR SELECT TO public USING (true)', sch);
    EXECUTE format('DROP POLICY IF EXISTS "Exercicios do grupo: leitura de quem le o grupo" ON %I.tb_grupos_exercicios', sch);
    EXECUTE format('DROP POLICY IF EXISTS "Leitura publica grupos_exercicios" ON %I.tb_grupos_exercicios', sch);
    EXECUTE format('CREATE POLICY "Leitura publica grupos_exercicios" ON %I.tb_grupos_exercicios FOR SELECT TO public USING (true)', sch);
    EXECUTE format('DROP POLICY IF EXISTS "Pastas: leitura do dono e do catalogo" ON %I.tb_pastas_treino', sch);
    EXECUTE format('DROP POLICY IF EXISTS "Pastas visiveis para autenticados" ON %I.tb_pastas_treino', sch);
    EXECUTE format('CREATE POLICY "Pastas visiveis para autenticados" ON %I.tb_pastas_treino FOR SELECT TO authenticated USING (true)', sch);
    EXECUTE format('DROP POLICY IF EXISTS "Vinculos de pasta: leitura de quem le a pasta" ON %I.tb_pastas_treino_grupos', sch);
    EXECUTE format('DROP POLICY IF EXISTS "Vinculos de pasta visiveis para autenticados" ON %I.tb_pastas_treino_grupos', sch);
    EXECUTE format('CREATE POLICY "Vinculos de pasta visiveis para autenticados" ON %I.tb_pastas_treino_grupos FOR SELECT TO authenticated USING (true)', sch);
    EXECUTE format('DROP POLICY IF EXISTS "Exercicios: catalogo global para visitante" ON %I.tb_exercicios', sch);
    EXECUTE format('DROP POLICY IF EXISTS "Exercicios: leitura para logados" ON %I.tb_exercicios', sch);
    EXECUTE format('DROP POLICY IF EXISTS "Leitura publica exercicios" ON %I.tb_exercicios', sch);
    EXECUTE format('CREATE POLICY "Leitura publica exercicios" ON %I.tb_exercicios FOR SELECT TO public USING (true)', sch);
    EXECUTE format('DROP POLICY IF EXISTS "Musculos: catalogo global para visitante" ON %I.grupos_musculares', sch);
    EXECUTE format('DROP POLICY IF EXISTS "Musculos: leitura para logados" ON %I.grupos_musculares', sch);
    EXECUTE format('DROP POLICY IF EXISTS "grupos_musculares_select_all" ON %I.grupos_musculares', sch);
    EXECUTE format('CREATE POLICY "grupos_musculares_select_all" ON %I.grupos_musculares FOR SELECT TO public USING (true)', sch);
    EXECUTE format('DROP FUNCTION IF EXISTS %I.physiq_pode_ler_grupo(uuid)', sch);
    EXECUTE format('ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA %I GRANT ALL ON TABLES TO anon', sch);
    EXECUTE format('ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA %I GRANT ALL ON SEQUENCES TO anon', sch);
    EXECUTE format('ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA %I GRANT TRUNCATE, TRIGGER, REFERENCES, MAINTAIN ON TABLES TO authenticated', sch);
    EXECUTE format($f$CREATE OR REPLACE FUNCTION %I.physiq_profiles_guard() RETURNS trigger LANGUAGE plpgsql AS $b$
      BEGIN
        IF current_setting('request.jwt.claims', true) IS NOT NULL
           AND current_setting('request.jwt.claims', true) <> ''
           AND (current_setting('request.jwt.claims', true)::jsonb->>'role') = 'authenticated'
           AND NOT %I.physiq_is_master() THEN
          IF NEW.professor_id IS DISTINCT FROM OLD.professor_id THEN
            NEW.professor_id := OLD.professor_id;
          END IF;
          -- W2: a conta do aluno é espelho do núcleo (trocar-token / espelho-nucleo), nunca escrita pelo app
          IF NEW.conta_id IS DISTINCT FROM OLD.conta_id THEN
            NEW.conta_id := OLD.conta_id;
          END IF;
        END IF;
        RETURN NEW;
      END $b$$f$, sch, sch);
    IF sch = 'public' THEN
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.app_config TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.app_config TO authenticated;$q$;
      EXECUTE $q$GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.edge_rate_limits_id_seq TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER ON public.exercicio_ordem_usuario TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.exercicio_ordem_usuario TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.exercicio_substituicao_usuario TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.exercicio_substituicao_usuario TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER ON public.grupos_musculares TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.grupos_musculares TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER ON public.physiq_assinaturas TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER ON public.physiq_assinaturas TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER ON public.physiq_avaliacoes TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.physiq_avaliacoes TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.physiq_avisos_plano TO authenticated;$q$;
      EXECUTE $q$GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.physiq_avisos_plano_id_seq TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.physiq_convites TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.physiq_integracoes TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER ON public.physiq_pagamentos TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER ON public.physiq_pagamentos TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.physiq_planos TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.physiq_planos_professor TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.physiq_planos_professor_hist TO authenticated;$q$;
      EXECUTE $q$GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.physiq_planos_professor_hist_id_seq TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.physiq_professores TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER ON public.physiq_profiles TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.physiq_profiles TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.physiq_recebimentos TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.physiq_recebimentos TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.physiq_registros_fotos TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.physiq_tags TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.physiq_tags TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.physiq_treinos_prontos TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.physiq_treinos_prontos_exercicios TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.physiq_treinos_prontos_grupos TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.physiq_user_tags TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.physiq_user_tags TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.tb_academia_pesos TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.tb_academia_pesos TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.tb_academias TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.tb_academias TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER ON public.tb_exercicio_comentarios TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.tb_exercicio_comentarios TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER ON public.tb_exercicios TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.tb_exercicios TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER ON public.tb_exercicios_usuario TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.tb_exercicios_usuario TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER ON public.tb_grupos_exercicios TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.tb_grupos_exercicios TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER ON public.tb_grupos_exercicios_usuario TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.tb_grupos_exercicios_usuario TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER ON public.tb_grupos_treino TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.tb_grupos_treino TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.tb_grupos_treino_perfis TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.tb_grupos_treino_perfis TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER ON public.tb_grupos_treino_usuario TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.tb_grupos_treino_usuario TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.tb_pastas_treino TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.tb_pastas_treino TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.tb_pastas_treino_grupos TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.tb_pastas_treino_grupos TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.tb_semana_dia_config TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.tb_semana_dia_config TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER ON public.tb_semana_treinos TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.tb_semana_treinos TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.tb_series_padrao_usuario TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.tb_series_padrao_usuario TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER ON public.tb_treino_concluido TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.tb_treino_concluido TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER ON public.tb_treino_dia_override TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.tb_treino_dia_override TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER ON public.tb_treino_series TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.tb_treino_series TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER ON public.treino_historico TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.treino_historico TO authenticated;$q$;
      EXECUTE $q$GRANT EXECUTE ON FUNCTION public.handle_new_user() TO anon, authenticated;$q$;
      EXECUTE $q$GRANT EXECUTE ON FUNCTION public.physiq_aluno_bloqueado(uuid) TO anon, authenticated;$q$;
      EXECUTE $q$ALTER FUNCTION public.physiq_aluno_bloqueado(uuid) RESET search_path;$q$;
      EXECUTE $q$GRANT EXECUTE ON FUNCTION public.physiq_avisos_tolerancia() TO anon, authenticated;$q$;
      EXECUTE $q$ALTER FUNCTION public.physiq_avisos_tolerancia() RESET search_path;$q$;
      EXECUTE $q$GRANT EXECUTE ON FUNCTION public.physiq_gerar_codigo_professor(text) TO anon, authenticated;$q$;
      EXECUTE $q$ALTER FUNCTION public.physiq_gerar_codigo_professor(text) RESET search_path;$q$;
      EXECUTE $q$GRANT EXECUTE ON FUNCTION public.physiq_meu_professor() TO anon, authenticated;$q$;
      EXECUTE $q$ALTER FUNCTION public.physiq_meu_professor() RESET search_path;$q$;
      EXECUTE $q$GRANT EXECUTE ON FUNCTION public.physiq_professor_acesso_ok(uuid) TO anon, authenticated;$q$;
      EXECUTE $q$GRANT EXECUTE ON FUNCTION public.physiq_professor_pode_convidar(uuid) TO anon, authenticated;$q$;
      EXECUTE $q$ALTER FUNCTION public.physiq_professor_pode_convidar(uuid) RESET search_path;$q$;
      EXECUTE $q$GRANT EXECUTE ON FUNCTION public.physiq_recebimentos_sync() TO anon, authenticated;$q$;
    END IF;
    IF sch = 'staging' THEN
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON staging.app_config TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.app_config TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON staging.edge_rate_limits TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.edge_rate_limits TO authenticated;$q$;
      EXECUTE $q$GRANT SELECT, UPDATE, USAGE ON SEQUENCE staging.edge_rate_limits_id_seq TO anon;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON staging.exercicio_ordem_usuario TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.exercicio_ordem_usuario TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON staging.exercicio_substituicao_usuario TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.exercicio_substituicao_usuario TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON staging.grupos_musculares TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.grupos_musculares TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER ON staging.physiq_assinaturas TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER ON staging.physiq_assinaturas TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON staging.physiq_avaliacoes TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.physiq_avaliacoes TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.physiq_avisos_plano TO authenticated;$q$;
      EXECUTE $q$GRANT SELECT, UPDATE, USAGE ON SEQUENCE staging.physiq_avisos_plano_id_seq TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.physiq_convites TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.physiq_integracoes TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER ON staging.physiq_pagamentos TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER ON staging.physiq_pagamentos TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.physiq_planos TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.physiq_planos_professor TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.physiq_planos_professor_hist TO authenticated;$q$;
      EXECUTE $q$GRANT SELECT, UPDATE, USAGE ON SEQUENCE staging.physiq_planos_professor_hist_id_seq TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.physiq_professores TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON staging.physiq_profiles TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.physiq_profiles TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON staging.physiq_recebimentos TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.physiq_recebimentos TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.physiq_registros_fotos TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON staging.physiq_tags TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.physiq_tags TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.physiq_treinos_prontos TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.physiq_treinos_prontos_exercicios TO authenticated;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.physiq_treinos_prontos_grupos TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON staging.physiq_user_tags TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.physiq_user_tags TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON staging.tb_academia_pesos TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.tb_academia_pesos TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON staging.tb_academias TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.tb_academias TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON staging.tb_exercicio_comentarios TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.tb_exercicio_comentarios TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON staging.tb_exercicios TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.tb_exercicios TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON staging.tb_exercicios_usuario TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.tb_exercicios_usuario TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON staging.tb_grupos_exercicios TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.tb_grupos_exercicios TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON staging.tb_grupos_exercicios_usuario TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.tb_grupos_exercicios_usuario TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON staging.tb_grupos_treino TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.tb_grupos_treino TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON staging.tb_grupos_treino_perfis TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.tb_grupos_treino_perfis TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON staging.tb_grupos_treino_usuario TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.tb_grupos_treino_usuario TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON staging.tb_pastas_treino TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.tb_pastas_treino TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON staging.tb_pastas_treino_grupos TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.tb_pastas_treino_grupos TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON staging.tb_semana_dia_config TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.tb_semana_dia_config TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON staging.tb_semana_treinos TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.tb_semana_treinos TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON staging.tb_series_padrao_usuario TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.tb_series_padrao_usuario TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON staging.tb_treino_concluido TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.tb_treino_concluido TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON staging.tb_treino_dia_override TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.tb_treino_dia_override TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON staging.tb_treino_series TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.tb_treino_series TO authenticated;$q$;
      EXECUTE $q$GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON staging.treino_historico TO anon;$q$;
      EXECUTE $q$GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON staging.treino_historico TO authenticated;$q$;
      EXECUTE $q$GRANT EXECUTE ON FUNCTION staging.check_rate_limit(uuid, text, integer, integer) TO anon, authenticated;$q$;
      EXECUTE $q$GRANT EXECUTE ON FUNCTION staging.handle_new_user() TO anon, authenticated;$q$;
      EXECUTE $q$GRANT EXECUTE ON FUNCTION staging.physiq_aluno_bloqueado(uuid) TO anon, authenticated;$q$;
      EXECUTE $q$ALTER FUNCTION staging.physiq_aluno_bloqueado(uuid) RESET search_path;$q$;
      EXECUTE $q$GRANT EXECUTE ON FUNCTION staging.physiq_gerar_codigo_professor(text) TO anon, authenticated;$q$;
      EXECUTE $q$ALTER FUNCTION staging.physiq_gerar_codigo_professor(text) RESET search_path;$q$;
      EXECUTE $q$GRANT EXECUTE ON FUNCTION staging.physiq_meu_professor() TO anon, authenticated;$q$;
      EXECUTE $q$ALTER FUNCTION staging.physiq_meu_professor() RESET search_path;$q$;
      EXECUTE $q$GRANT EXECUTE ON FUNCTION staging.physiq_professor_acesso_ok(uuid) TO anon, authenticated;$q$;
      EXECUTE $q$GRANT EXECUTE ON FUNCTION staging.physiq_professor_pode_convidar(uuid) TO anon, authenticated;$q$;
      EXECUTE $q$ALTER FUNCTION staging.physiq_professor_pode_convidar(uuid) RESET search_path;$q$;
      EXECUTE $q$GRANT EXECUTE ON FUNCTION staging.physiq_recebimentos_sync() TO anon, authenticated;$q$;
    END IF;
  END LOOP;
END
$rev$;
