# Adds YAML Schema support for VSCode users with the YAML extension installed. This enables features like validation and autocompletion based on the provided schema.
# yaml-language-server: $schema=https://unpkg.com/@powersync/service-sync-rules@latest/schema/sync_rules.json
config:
  edition: 3

streams:
  global:
    auto_subscribe: true
    queries:
      - SELECT * FROM tb_exercicios
      - SELECT * FROM grupos_musculares

  grupos_por_perfil:
    auto_subscribe: true
    queries:
      - SELECT tb_grupos_treino.* FROM tb_grupos_treino
        JOIN tb_grupos_treino_perfis p ON p.grupo_id = tb_grupos_treino.id
        WHERE p.user_id = auth.user_id()
      - SELECT tb_grupos_exercicios.* FROM tb_grupos_exercicios
        JOIN tb_grupos_treino_perfis p ON p.grupo_id = tb_grupos_exercicios.grupo_id
        WHERE p.user_id = auth.user_id()

  by_user:
    auto_subscribe: true
    queries:
      - SELECT * FROM tb_treino_series WHERE user_id = auth.user_id()
      - SELECT * FROM tb_treino_concluido WHERE user_id = auth.user_id()
      - SELECT * FROM tb_treino_dia_override WHERE user_id = auth.user_id()
      - SELECT * FROM treino_historico WHERE user_id = auth.user_id()
      - SELECT * FROM physiq_profiles WHERE id = auth.user_id()
      - SELECT * FROM exercicio_ordem_usuario WHERE user_id = auth.user_id()
      - SELECT * FROM tb_grupos_treino_usuario WHERE user_id = auth.user_id()
      - SELECT * FROM tb_exercicios_usuario WHERE user_id = auth.user_id()
      - SELECT * FROM tb_grupos_exercicios_usuario WHERE user_id = auth.user_id()
      - SELECT * FROM tb_exercicio_comentarios WHERE user_id = auth.user_id()
      - SELECT * FROM tb_semana_treinos WHERE user_id = auth.user_id()
